# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/speqtral/XilinxVivado/Cmod-s7-uart-hello-world/Cmod-s7-uart-hello-world.srcs/sources_1/bd/uart/ip/uart_microblaze_mcs_0_0/uart_microblaze_mcs_0_0.xci
# IP: The module: 'uart_microblaze_mcs_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Users/speqtral/XilinxVivado/Cmod-s7-uart-hello-world/Cmod-s7-uart-hello-world.srcs/sources_1/bd/uart/ip/uart_microblaze_mcs_0_0/bd_0/bd_7d4e.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_7d4e || ORIG_REF_NAME==bd_7d4e} -quiet] -quiet

# IP: c:/Users/speqtral/XilinxVivado/Cmod-s7-uart-hello-world/Cmod-s7-uart-hello-world.srcs/sources_1/bd/uart/ip/uart_microblaze_mcs_0_0/bd_0/ip/ip_0/bd_7d4e_microblaze_I_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_7d4e_microblaze_I_0 || ORIG_REF_NAME==bd_7d4e_microblaze_I_0} -quiet] -quiet

# IP: c:/Users/speqtral/XilinxVivado/Cmod-s7-uart-hello-world/Cmod-s7-uart-hello-world.srcs/sources_1/bd/uart/ip/uart_microblaze_mcs_0_0/bd_0/ip/ip_1/bd_7d4e_rst_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_7d4e_rst_0_0 || ORIG_REF_NAME==bd_7d4e_rst_0_0} -quiet] -quiet

# IP: c:/Users/speqtral/XilinxVivado/Cmod-s7-uart-hello-world/Cmod-s7-uart-hello-world.srcs/sources_1/bd/uart/ip/uart_microblaze_mcs_0_0/bd_0/ip/ip_2/bd_7d4e_ilmb_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_7d4e_ilmb_0 || ORIG_REF_NAME==bd_7d4e_ilmb_0} -quiet] -quiet

# IP: c:/Users/speqtral/XilinxVivado/Cmod-s7-uart-hello-world/Cmod-s7-uart-hello-world.srcs/sources_1/bd/uart/ip/uart_microblaze_mcs_0_0/bd_0/ip/ip_3/bd_7d4e_dlmb_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_7d4e_dlmb_0 || ORIG_REF_NAME==bd_7d4e_dlmb_0} -quiet] -quiet

# IP: c:/Users/speqtral/XilinxVivado/Cmod-s7-uart-hello-world/Cmod-s7-uart-hello-world.srcs/sources_1/bd/uart/ip/uart_microblaze_mcs_0_0/bd_0/ip/ip_4/bd_7d4e_dlmb_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_7d4e_dlmb_cntlr_0 || ORIG_REF_NAME==bd_7d4e_dlmb_cntlr_0} -quiet] -quiet

# IP: c:/Users/speqtral/XilinxVivado/Cmod-s7-uart-hello-world/Cmod-s7-uart-hello-world.srcs/sources_1/bd/uart/ip/uart_microblaze_mcs_0_0/bd_0/ip/ip_5/bd_7d4e_ilmb_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_7d4e_ilmb_cntlr_0 || ORIG_REF_NAME==bd_7d4e_ilmb_cntlr_0} -quiet] -quiet

# IP: c:/Users/speqtral/XilinxVivado/Cmod-s7-uart-hello-world/Cmod-s7-uart-hello-world.srcs/sources_1/bd/uart/ip/uart_microblaze_mcs_0_0/bd_0/ip/ip_6/bd_7d4e_lmb_bram_I_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_7d4e_lmb_bram_I_0 || ORIG_REF_NAME==bd_7d4e_lmb_bram_I_0} -quiet] -quiet

# IP: c:/Users/speqtral/XilinxVivado/Cmod-s7-uart-hello-world/Cmod-s7-uart-hello-world.srcs/sources_1/bd/uart/ip/uart_microblaze_mcs_0_0/bd_0/ip/ip_7/bd_7d4e_iomodule_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_7d4e_iomodule_0_0 || ORIG_REF_NAME==bd_7d4e_iomodule_0_0} -quiet] -quiet

# XDC: c:/Users/speqtral/XilinxVivado/Cmod-s7-uart-hello-world/Cmod-s7-uart-hello-world.srcs/sources_1/bd/uart/ip/uart_microblaze_mcs_0_0/bd_0/ip/ip_0/bd_7d4e_microblaze_I_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_7d4e_microblaze_I_0 || ORIG_REF_NAME==bd_7d4e_microblaze_I_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/speqtral/XilinxVivado/Cmod-s7-uart-hello-world/Cmod-s7-uart-hello-world.srcs/sources_1/bd/uart/ip/uart_microblaze_mcs_0_0/bd_0/ip/ip_0/bd_7d4e_microblaze_I_0_ooc_debug.xdc

# XDC: c:/Users/speqtral/XilinxVivado/Cmod-s7-uart-hello-world/Cmod-s7-uart-hello-world.srcs/sources_1/bd/uart/ip/uart_microblaze_mcs_0_0/bd_0/ip/ip_1/bd_7d4e_rst_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_7d4e_rst_0_0 || ORIG_REF_NAME==bd_7d4e_rst_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/speqtral/XilinxVivado/Cmod-s7-uart-hello-world/Cmod-s7-uart-hello-world.srcs/sources_1/bd/uart/ip/uart_microblaze_mcs_0_0/bd_0/ip/ip_1/bd_7d4e_rst_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_7d4e_rst_0_0 || ORIG_REF_NAME==bd_7d4e_rst_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/speqtral/XilinxVivado/Cmod-s7-uart-hello-world/Cmod-s7-uart-hello-world.srcs/sources_1/bd/uart/ip/uart_microblaze_mcs_0_0/bd_0/ip/ip_2/bd_7d4e_ilmb_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_7d4e_ilmb_0 || ORIG_REF_NAME==bd_7d4e_ilmb_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/speqtral/XilinxVivado/Cmod-s7-uart-hello-world/Cmod-s7-uart-hello-world.srcs/sources_1/bd/uart/ip/uart_microblaze_mcs_0_0/bd_0/ip/ip_3/bd_7d4e_dlmb_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_7d4e_dlmb_0 || ORIG_REF_NAME==bd_7d4e_dlmb_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/speqtral/XilinxVivado/Cmod-s7-uart-hello-world/Cmod-s7-uart-hello-world.srcs/sources_1/bd/uart/ip/uart_microblaze_mcs_0_0/bd_0/ip/ip_6/bd_7d4e_lmb_bram_I_0_ooc.xdc

# XDC: c:/Users/speqtral/XilinxVivado/Cmod-s7-uart-hello-world/Cmod-s7-uart-hello-world.srcs/sources_1/bd/uart/ip/uart_microblaze_mcs_0_0/bd_0/ip/ip_7/bd_7d4e_iomodule_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_7d4e_iomodule_0_0 || ORIG_REF_NAME==bd_7d4e_iomodule_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/speqtral/XilinxVivado/Cmod-s7-uart-hello-world/Cmod-s7-uart-hello-world.srcs/sources_1/bd/uart/ip/uart_microblaze_mcs_0_0/bd_0/bd_7d4e_ooc.xdc

# XDC: c:/Users/speqtral/XilinxVivado/Cmod-s7-uart-hello-world/Cmod-s7-uart-hello-world.srcs/sources_1/bd/uart/ip/uart_microblaze_mcs_0_0/uart_microblaze_mcs_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'uart_microblaze_mcs_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/speqtral/XilinxVivado/Cmod-s7-uart-hello-world/Cmod-s7-uart-hello-world.srcs/sources_1/bd/uart/ip/uart_microblaze_mcs_0_0/uart_microblaze_mcs_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'uart_microblaze_mcs_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/speqtral/XilinxVivado/Cmod-s7-uart-hello-world/Cmod-s7-uart-hello-world.srcs/sources_1/bd/uart/ip/uart_microblaze_mcs_0_0/uart_microblaze_mcs_0_0.xci
# IP: The module: 'uart_microblaze_mcs_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Users/speqtral/XilinxVivado/Cmod-s7-uart-hello-world/Cmod-s7-uart-hello-world.srcs/sources_1/bd/uart/ip/uart_microblaze_mcs_0_0/bd_0/bd_7d4e.bd
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_7d4e || ORIG_REF_NAME==bd_7d4e} -quiet] -quiet

# IP: c:/Users/speqtral/XilinxVivado/Cmod-s7-uart-hello-world/Cmod-s7-uart-hello-world.srcs/sources_1/bd/uart/ip/uart_microblaze_mcs_0_0/bd_0/ip/ip_0/bd_7d4e_microblaze_I_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_7d4e_microblaze_I_0 || ORIG_REF_NAME==bd_7d4e_microblaze_I_0} -quiet] -quiet

# IP: c:/Users/speqtral/XilinxVivado/Cmod-s7-uart-hello-world/Cmod-s7-uart-hello-world.srcs/sources_1/bd/uart/ip/uart_microblaze_mcs_0_0/bd_0/ip/ip_1/bd_7d4e_rst_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_7d4e_rst_0_0 || ORIG_REF_NAME==bd_7d4e_rst_0_0} -quiet] -quiet

# IP: c:/Users/speqtral/XilinxVivado/Cmod-s7-uart-hello-world/Cmod-s7-uart-hello-world.srcs/sources_1/bd/uart/ip/uart_microblaze_mcs_0_0/bd_0/ip/ip_2/bd_7d4e_ilmb_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_7d4e_ilmb_0 || ORIG_REF_NAME==bd_7d4e_ilmb_0} -quiet] -quiet

# IP: c:/Users/speqtral/XilinxVivado/Cmod-s7-uart-hello-world/Cmod-s7-uart-hello-world.srcs/sources_1/bd/uart/ip/uart_microblaze_mcs_0_0/bd_0/ip/ip_3/bd_7d4e_dlmb_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_7d4e_dlmb_0 || ORIG_REF_NAME==bd_7d4e_dlmb_0} -quiet] -quiet

# IP: c:/Users/speqtral/XilinxVivado/Cmod-s7-uart-hello-world/Cmod-s7-uart-hello-world.srcs/sources_1/bd/uart/ip/uart_microblaze_mcs_0_0/bd_0/ip/ip_4/bd_7d4e_dlmb_cntlr_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_7d4e_dlmb_cntlr_0 || ORIG_REF_NAME==bd_7d4e_dlmb_cntlr_0} -quiet] -quiet

# IP: c:/Users/speqtral/XilinxVivado/Cmod-s7-uart-hello-world/Cmod-s7-uart-hello-world.srcs/sources_1/bd/uart/ip/uart_microblaze_mcs_0_0/bd_0/ip/ip_5/bd_7d4e_ilmb_cntlr_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_7d4e_ilmb_cntlr_0 || ORIG_REF_NAME==bd_7d4e_ilmb_cntlr_0} -quiet] -quiet

# IP: c:/Users/speqtral/XilinxVivado/Cmod-s7-uart-hello-world/Cmod-s7-uart-hello-world.srcs/sources_1/bd/uart/ip/uart_microblaze_mcs_0_0/bd_0/ip/ip_6/bd_7d4e_lmb_bram_I_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_7d4e_lmb_bram_I_0 || ORIG_REF_NAME==bd_7d4e_lmb_bram_I_0} -quiet] -quiet

# IP: c:/Users/speqtral/XilinxVivado/Cmod-s7-uart-hello-world/Cmod-s7-uart-hello-world.srcs/sources_1/bd/uart/ip/uart_microblaze_mcs_0_0/bd_0/ip/ip_7/bd_7d4e_iomodule_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_7d4e_iomodule_0_0 || ORIG_REF_NAME==bd_7d4e_iomodule_0_0} -quiet] -quiet

# XDC: c:/Users/speqtral/XilinxVivado/Cmod-s7-uart-hello-world/Cmod-s7-uart-hello-world.srcs/sources_1/bd/uart/ip/uart_microblaze_mcs_0_0/bd_0/ip/ip_0/bd_7d4e_microblaze_I_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_7d4e_microblaze_I_0 || ORIG_REF_NAME==bd_7d4e_microblaze_I_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/speqtral/XilinxVivado/Cmod-s7-uart-hello-world/Cmod-s7-uart-hello-world.srcs/sources_1/bd/uart/ip/uart_microblaze_mcs_0_0/bd_0/ip/ip_0/bd_7d4e_microblaze_I_0_ooc_debug.xdc

# XDC: c:/Users/speqtral/XilinxVivado/Cmod-s7-uart-hello-world/Cmod-s7-uart-hello-world.srcs/sources_1/bd/uart/ip/uart_microblaze_mcs_0_0/bd_0/ip/ip_1/bd_7d4e_rst_0_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_7d4e_rst_0_0 || ORIG_REF_NAME==bd_7d4e_rst_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/speqtral/XilinxVivado/Cmod-s7-uart-hello-world/Cmod-s7-uart-hello-world.srcs/sources_1/bd/uart/ip/uart_microblaze_mcs_0_0/bd_0/ip/ip_1/bd_7d4e_rst_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_7d4e_rst_0_0 || ORIG_REF_NAME==bd_7d4e_rst_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/speqtral/XilinxVivado/Cmod-s7-uart-hello-world/Cmod-s7-uart-hello-world.srcs/sources_1/bd/uart/ip/uart_microblaze_mcs_0_0/bd_0/ip/ip_2/bd_7d4e_ilmb_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_7d4e_ilmb_0 || ORIG_REF_NAME==bd_7d4e_ilmb_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/speqtral/XilinxVivado/Cmod-s7-uart-hello-world/Cmod-s7-uart-hello-world.srcs/sources_1/bd/uart/ip/uart_microblaze_mcs_0_0/bd_0/ip/ip_3/bd_7d4e_dlmb_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_7d4e_dlmb_0 || ORIG_REF_NAME==bd_7d4e_dlmb_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/speqtral/XilinxVivado/Cmod-s7-uart-hello-world/Cmod-s7-uart-hello-world.srcs/sources_1/bd/uart/ip/uart_microblaze_mcs_0_0/bd_0/ip/ip_6/bd_7d4e_lmb_bram_I_0_ooc.xdc

# XDC: c:/Users/speqtral/XilinxVivado/Cmod-s7-uart-hello-world/Cmod-s7-uart-hello-world.srcs/sources_1/bd/uart/ip/uart_microblaze_mcs_0_0/bd_0/ip/ip_7/bd_7d4e_iomodule_0_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_7d4e_iomodule_0_0 || ORIG_REF_NAME==bd_7d4e_iomodule_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/speqtral/XilinxVivado/Cmod-s7-uart-hello-world/Cmod-s7-uart-hello-world.srcs/sources_1/bd/uart/ip/uart_microblaze_mcs_0_0/bd_0/bd_7d4e_ooc.xdc

# XDC: c:/Users/speqtral/XilinxVivado/Cmod-s7-uart-hello-world/Cmod-s7-uart-hello-world.srcs/sources_1/bd/uart/ip/uart_microblaze_mcs_0_0/uart_microblaze_mcs_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'uart_microblaze_mcs_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/speqtral/XilinxVivado/Cmod-s7-uart-hello-world/Cmod-s7-uart-hello-world.srcs/sources_1/bd/uart/ip/uart_microblaze_mcs_0_0/uart_microblaze_mcs_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'uart_microblaze_mcs_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
