# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/digilent-xdc/Cmod-S7-25-Master.xdc

# Block Designs: bd/uart/uart.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uart || ORIG_REF_NAME==uart} -quiet] -quiet

# IP: bd/uart/ip/uart_microblaze_mcs_0_0/uart_microblaze_mcs_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uart_microblaze_mcs_0_0 || ORIG_REF_NAME==uart_microblaze_mcs_0_0} -quiet] -quiet

# XDC: bd/uart/uart_ooc.xdc
